import math

num_bits = 32
n = 1024
header = f'''\
//
// Sine wave lookup table. Generated by scripts/generate_sin_table.py. DO NOT MODIFY.
//
#ifndef SIN_H
#define SIN_H

#include <stdint.h>

#define N_WAVE {n}
#define LOG2_N_WAVE {int(math.log2(n))}

const int32_t sine_tbl[N_WAVE-N_WAVE/4] = {{
'''

footer = """\
};

#endif
"""

def main():
    out_file = "source/sin.h"
    with open(out_file, "w") as f:
        f.write(header)
        for i in range(int(n * 3/4)):
            d = float(i) * 2 * math.pi / n
            f.write(f'    {int((2**(num_bits-1)) - 1) * math.sin(d):.0f},\n')
        f.write(footer)
        f.flush()

if __name__ == "__main__":
    main()
